version: "3.9"

services:

  # db:
  #   image: postgres:14.3-alpine3.15
  #   ports:
  #     - "5432:5432"
  #   hostname: localhost
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: d_project

  redis:
    image: redis
    ports:
      - "6379:6379"

  worker:
    build:
      context:  .
    hostname: worker
    entrypoint: celery
    command: -A netology_pd_diplom worker -l info
    links:
      - redis
    depends_on:
      - redis

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A netology_pd_diplom flower
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"

  app:
    build: ./
    ports:
      - "8000:8000"
    env_file:
      - .env
#    depends_on:
#      - db